export enum CommentsActionTypes {
  COMMENTS_GET_PENDING = 'COMMENTS_GET_PENDING',
  COMMENTS_GET_SUCCESS = 'COMMENTS_GET_SUCCESS',
  COMMENTS_GET_ERROR = 'COMMENTS_GET_ERROR',
  ALL_COMMENTS_GET_PENDING = 'ALL_COMMENTS_GET_PENDING',
  ALL_COMMENTS_GET_SUCCESS = 'ALL_COMMENTS_GET_SUCCESS',
  ALL_COMMENTS_GET_ERROR = 'ALL_COMMENTS_GET_ERROR',
  COMMENTS_ADD_SUCCESS = 'COMMENTS_ADD_SUCCESS',
  COMMENTS_ADD_ERROR = 'COMMENTS_ADD_ERROR',
}
